---
title: "CASA Low-income Tenure"
output: csv table
---

This script builds the 2016 Community of Concern Dataset using the prescribed methodology located here:   [GitHub Documentation](https://github.com/BayAreaMetro/Spatial-Analysis-Mapping-Projects/tree/master/Project-Documentation/Communities-of-Concern). 

It uses the censusapi library which is documented here: [CensusAPI](https://hrecht.github.io/censusapi/index.html)

```{r message=FALSE, warning=FALSE}
library(censusapi)
library(readr)
library(dplyr)
#Community of Concern Spatial Processing
library(censusapi)
library(readr)
library(dplyr)
### Install Mapping Libraries
# install.packages("leaflet")
# install.packages("rgdal")
# install.packages("geojsonio")
# install.packages("spdplyr")
# install.packages("rmapshaper")
# install.packages("jsonlite")
#install.packages("knitr")
#library(leaflet)
library(jsonlite)
library(rgdal)
#library(geojsonio)
library(spdplyr)
library(rmapshaper)
library(knitr)
library(tidyr)

#setwd("~/Documents/Github_Documentation/Spatial-Analysis-Mapping-Projects/Project-Documentation/Communities-of-Concern/Data")
#This key is private and should not be shared via GitHub.  It is here for internal use only.  This portion of the code should be removed when sharing to Github.
Sys.getenv("1aa6908e05aacb828e007966689cbb4948736392")
# Add key to .Renviron
Sys.setenv(CENSUS_KEY='1aa6908e05aacb828e007966689cbb4948736392')
# Reload .Renviron
readRenviron("~/.Renviron")
# Check to see that the expected key is output in your R console
Sys.getenv("CENSUS_KEY")
#Provides list of APIs 
apis <- listCensusApis()
```

```{r message=FALSE, warning=FALSE}
ACS_COC_SelectedVars <- read_csv("ACS_Table_Variables_lowincome.csv")
acs_vars <- ACS_COC_SelectedVars$ACS_Table_Variable
#rm(selectedData)
selectedData <- getCensus(name="acs/acs5", vintage=2016,
                          vars=acs_vars, 
                          region="tract:*", 
                          regionin="state:06+county:001,013,041,055,075,081,085,095,097")
head(selectedData)
```

#### Calculate COC variables from selectedData

```{r message=FALSE, warning=FALSE}
selectedData$GEOID <- paste(selectedData$state,selectedData$county,selectedData$tract,sep="")
selectedData$STATE <- selectedData$state
selectedData$COUNTY_FIPS <- selectedData$county
selectedData$TRACT <- selectedData$tract
selectedData$TOT_POP_MIN <- selectedData$B03002_001E 
selectedData$TOT_POP_SEN <- selectedData$B01001_001E
selectedData$TOT_POP_POV <- selectedData$C17002_001E
selectedData$TOT_POP_CIV_NI <- selectedData$C18108_001E
selectedData$TOT_HH <- selectedData$B08201_001E
selectedData$TOT_FAM <- selectedData$B11004_001E
selectedData$TOT_POP_OVER5 <- selectedData$B16005_001E
selectedData$POP_MINORITY <- selectedData$B03002_001E - selectedData$B03002_003E
selectedData$POP_OVER75 <- selectedData$B01001_023E + selectedData$B01001_024E + selectedData$B01001_025E + selectedData$B01001_047E + selectedData$B01001_048E + selectedData$B01001_049E
selectedData$POP_SPFAM <- selectedData$B11004_010E + selectedData$B11004_016E
selectedData$POP_LEP<- selectedData$B16005_007E + selectedData$B16005_008E + selectedData$B16005_012E + selectedData$B16005_013E + selectedData$B16005_017E + selectedData$B16005_018E + selectedData$B16005_022E + selectedData$B16005_023E + selectedData$B16005_029E + selectedData$B16005_030E + selectedData$B16005_034E + selectedData$B16005_035E + selectedData$B16005_039E + selectedData$B16005_040E + selectedData$B16005_044E + selectedData$B16005_045E
selectedData$POP_BELOW200 <- selectedData$C17002_001E - selectedData$C17002_008E
selectedData$POP_DISABILITY <- selectedData$C18108_001E - (selectedData$C18108_005E + selectedData$C18108_009E + selectedData$C18108_013E)
selectedData$POP_HUS_RENT50 <- selectedData$B25070_010E
selectedData$POP_ZVHHS <- selectedData$B08201_002E
selectedData$PCT_OVER75 <- ifelse(selectedData$B01001_001E == 0,0,((selectedData$B01001_023E + selectedData$B01001_024E + selectedData$B01001_025E + selectedData$B01001_047E + selectedData$B01001_048E + selectedData$B01001_049E)/selectedData$B01001_001E))
selectedData$PCT_MINORITY <- ifelse(selectedData$B03002_001E == 0,0,((selectedData$B03002_001E - selectedData$B03002_003E)/selectedData$B03002_001E))
selectedData$PCT_SPFAM <- ifelse(selectedData$B11004_001E == 0,0,((selectedData$B11004_010E + selectedData$B11004_016E)/selectedData$B11004_001E))
selectedData$PCT_LEP <- ifelse(selectedData$B16005_001E == 0,0,((selectedData$B16005_007E + selectedData$B16005_008E + selectedData$B16005_012E + selectedData$B16005_013E + selectedData$B16005_017E + selectedData$B16005_018E + selectedData$B16005_022E + selectedData$B16005_023E + selectedData$B16005_029E + selectedData$B16005_030E + selectedData$B16005_034E + selectedData$B16005_035E + selectedData$B16005_039E + selectedData$B16005_040E + selectedData$B16005_044E + selectedData$B16005_045E)/selectedData$B16005_001E))
selectedData$PCT_BELOW200 <- ifelse(selectedData$C17002_001E == 0,0,((selectedData$C17002_001E - selectedData$C17002_008E)/selectedData$C17002_001E))
selectedData$PCT_DISAB <- ifelse(selectedData$C18108_001E == 0,0,((selectedData$C18108_001E - (selectedData$C18108_005E + selectedData$C18108_009E + selectedData$C18108_013E))/selectedData$C18108_001E))
selectedData$PCT_ZVHHS <- ifelse(selectedData$B08201_001E == 0,0,(selectedData$B08201_002E/selectedData$B08201_001E))
selectedData$PCT_HUS_RENT50 <- ifelse(selectedData$B08201_001E == 0,0,(selectedData$B25070_010E/selectedData$B08201_001E))

head(selectedData)
```

#### Export Final Table to CSV 
```{r}
write.csv(selectedData, "lowincomeTenure_ACS2016_tbl.csv")
```
