---
title: "CASA Low-income Tenure"
output: csv table
---

This script builds the 2016 Community of Concern Dataset using the prescribed methodology located here:   [GitHub Documentation](https://github.com/BayAreaMetro/Spatial-Analysis-Mapping-Projects/tree/master/Project-Documentation/Communities-of-Concern). 

It uses the censusapi library which is documented here: [CensusAPI](https://hrecht.github.io/censusapi/index.html)

```{r message=FALSE, warning=FALSE}
library(censusapi)
library(readr)
library(dplyr)
#Community of Concern Spatial Processing
library(censusapi)
library(readr)
library(dplyr)
### Install Mapping Libraries
# install.packages("leaflet")
# install.packages("rgdal")
# install.packages("geojsonio")
# install.packages("spdplyr")
# install.packages("rmapshaper")
# install.packages("jsonlite")
#install.packages("knitr")
#library(leaflet)
library(jsonlite)
library(rgdal)
#library(geojsonio)
library(spdplyr)
library(rmapshaper)
library(knitr)
library(tidyr)

#setwd("~/Documents/Github_Documentation/Spatial-Analysis-Mapping-Projects/Project-Documentation/Communities-of-Concern/Data")
#This key is private and should not be shared via GitHub.  It is here for internal use only.  This portion of the code should be removed when sharing to Github.
Sys.getenv("1aa6908e05aacb828e007966689cbb4948736392")
# Add key to .Renviron
Sys.setenv(CENSUS_KEY='1aa6908e05aacb828e007966689cbb4948736392')
# Reload .Renviron
readRenviron("~/.Renviron")
# Check to see that the expected key is output in your R console
Sys.getenv("CENSUS_KEY")
#Provides list of APIs 
apis <- listCensusApis()
```

```{r message=FALSE, warning=FALSE}
ACS_COC_SelectedVars <- read_csv("ACS_Table_Variables_lowincome.csv")
acs_vars <- ACS_COC_SelectedVars$ACS_Table_Variable
#rm(selectedData)
selectedData <- getCensus(name="acs/acs5", vintage=2016,
                          vars=acs_vars, 
                          region="tract:*", 
                          regionin="state:06+county:001,013,041,055,075,081,085,095,097")
head(selectedData)
```

#### Export Final Table to CSV 
```{r}
write.csv(selectedData, "lowincomeTenure_ACS2016_tbl.csv")
```
